"""
Constantes : 
BUILD
STABILITY
ERROR
"""

# ============================
# Bases & Classification
# ============================
DEFAULT_COST_BUILD_CLASSIFICATION = 0.0    # Coût neutre pour la connexion base <-> classification
DEFAULT_STABILITY_BUILD_CLASSIFICATION = 1.0  # Stabilité maximale (1 = parfait)
DEFAULT_ERROR_BUILD_CLASSIFICATION = 0.0  

# ============================
# Liaisons entre Bases
# ============================

DEFAULT_COST_BUILD_AT = 0.5
DEFAULT_COST_BUILD_CG = 0.4

DEFAULT_STABILITY_BUILD_AT = 0.9
DEFAULT_STABILITY_BUILD_CG = 0.9
DEFAULT_ERROR_BUILD_AT = 0.1
DEFAULT_ERROR_BUILD_CG = 0.05

# ============================
# Degeneracy
# ============================
DEFAULT_COST_BUILD_DEGEN = 0.05
DEFAULT_STABILITY_BUILD_DEGEN = 0.0
DEFAULT_ERROR_BUILD_DEGEN = 0.0

# ============================
# Motifs
# ============================
DEFAULT_COST_BUILD_MOTIF_A = 0.3
DEFAULT_STABILITY_BUILD_MOTIF_A = 0.8
DEFAULT_ERROR_BUILD_MOTIF_A = 0.2

DEFAULT_COST_BUILD_MOTIF_T = 0.3
DEFAULT_STABILITY_BUILD_MOTIF_T = 0.8
DEFAULT_ERROR_BUILD_MOTIF_T = 0.2

DEFAULT_COST_BUILD_MOTIF_EXON_INTRO = 0.2
DEFAULT_STABILITY_BUILD_MOTIF_EXON_INTRO = 0.8
DEFAULT_ERROR_BUILD_MOTIF_EXON_INTRO = 0.1

DEFAULT_COST_BUILD_MOTIF_ACTG = 0.3
DEFAULT_STABILITY_BUILD_MOTIF_ACTG = 0.7
DEFAULT_ERROR_BUILD_MOTIF_ACTG = 0.1

# ============================
# Processus
# ============================
DEFAULT_COST_BUILD_PRO_MOD = 0.2
DEFAULT_STABILITY_BUILD_PRO_MOD = 0.9
DEFAULT_ERROR_BUILD_PRO_MOD = 0.05

DEFAULT_COST_BUILD_PRO_COR = 0.1
DEFAULT_STABILITY_BUILD_PRO_COR = 0.95
DEFAULT_ERROR_BUILD_PRO_COR = 0.02

# ============================
# Code Correcteur
# ============================

DEFAULT_COST_BUILD_COR_COR = 0.3
DEFAULT_STABILITY_BUILD_COR_COR = 0.0
DEFAULT_ERROR_BUILD_COR_COR = 0.2

# ============================
# Code
# ============================
DEFAULT_COST_BUILD_CODE = 0.05
DEFAULT_STABILITY_BUILD_CODE = 0.9
DEFAULT_ERROR_BUILD_CODE = 0.02

# ============================
# Régulation
# ============================
DEFAULT_COST_BUILD_ELEM_ENHANCER_PRO = 0.2
DEFAULT_STABILITY_BUILD_ELEM_ENHANCER_PRO = 0.85
DEFAULT_ERROR_BUILD_ELEM_ENHANCER_PRO = 0.05

DEFAULT_COST_BUILD_ELEM_SILENCER_PRO = 0.3
DEFAULT_STABILITY_BUILD_ELEM_SILENCER_PRO = 0.80
DEFAULT_ERROR_BUILD_ELEM_SILENCER_PRO = 0.07

DEFAULT_COST_BUILD_ELEM_ENHANCER_GEN = 0.25
DEFAULT_STABILITY_BUILD_ELEM_ENHANCER_GEN = 0.80
DEFAULT_ERROR_BUILD_ELEM_ENHANCER_GEN = 0.05

DEFAULT_COST_BUILD_ELEM_SILENCER_GEN = 0.35
DEFAULT_STABILITY_BUILD_ELEM_SILENCER_GEN = 0.75
DEFAULT_ERROR_BUILD_ELEM_SILENCER_GEN = 0.07

DEFAULT_COST_BUILD_TF1 = 0.2
DEFAULT_STABILITY_TF1 = 0.90
DEFAULT_ERROR_TF1 = 0.03

DEFAULT_COST_BUILD_TF2 = 0.25
DEFAULT_STABILITY_TF2 = 0.88
DEFAULT_ERROR_TF2 = 0.04

# ============================
# Segments (3-mers)
# ============================
DEFAULT_COST_BUILD_TF2 = 0.25
DEFAULT_STABILITY_TF2 = 0.88
DEFAULT_ERROR_TF2 = 0.04

DEFAULT_COST_BUILD_3MER_BUILD = 0.25
DEFAULT_STABILITY_3MER_BUILD = 0.65
DEFAULT_ERROR_3MER_BUILD = 0.1

DEFAULT_COST_BUILD_3MER_COM = 0.35
DEFAULT_STABILITY_3MER_COM = 0.75
DEFAULT_ERROR_3MER_COM = 0.05
